### ISSUE TITLE
Ennemy still hitting after death

### ISSUE THREAD

**Issue by MathisPERRIN** [rparrett/taipo#8]
When an ennemy is hitting the house. If you kill him he desn't die, continue hitting and isn't focused by towers anymore

**Comment by rparrett** [comment]
Thanks for the report!

I fixed this in https://github.com/rparrett/taipo/commit/1a38cfc01fb5f6b7588c6e8809d12778723cab74 and will upload a new version whenever it finishes building.

**Comment by rparrett** [comment]
0.3.2 has been deployed to itch. Thanks again.
